### ISSUE TITLE
メニュー投稿機能の実施

### ISSUE THREAD

**Issue by stivan622** [fitness-app/fitness_app#20]
- [ ] #19 と #11 を参考に自分でTODOを作ってissueに取り組む

- このissueにやったこと、現状を書いておく  
他の人がこれなんだっけてなった時に検索して分かると捗るから  
あとアドバイスできる

- 時間がかかりそうな、思い機能があったらissueを作って後回し  
簡易版の完成最優先

**Comment by MitoShimada** [comment]
# TODO

- [ ]  CRUD機能の完成
- [ ] indexアクション関連は削除して、Top#indexにツイート表示
- [ ] 動画投稿機能
- [ ] どのユーザーが投稿したか分かるようにする(user_idに投稿者のidを入れる)
- [ ] バリデーション
- [ ] アソシエーション（ユーザーとの）
#20

**Comment by MitoShimada** [comment]
フォームつくってcontent書けるようにしました
```
def menu_params
  params.fetch(:menu, {})
end
```
http://o.inchiki.jp/obbr/181
paramsfetchってなんだろうと思ってぐぐったけどよくわからないまま上手くいく

**Comment by MitoShimada** [comment]
```
uirb(main):001:0> user = User.find(1)
  User Load (1.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
=> #<User id: 1, email: "aaa@aaa", name: "aaa", avatar: "___________1_.png", profile: nil, created_at: "2016-10-17 11:34:56", updated_at: "2016-10-17 11:34:56">
irb(main):002:0> user.menus
  Menu Load (0.4ms)  SELECT "menus".* FROM "menus" WHERE "menus"."user_id" = $1  [["user_id", 1]]
=> #<ActiveRecord::Associations::CollectionProxy [#<Menu id: 6, content: "hhh", movie: nil, user_id: 1, created_at: "2016-10-17 11:28:48", updated_at: "2016-10-17 11:44:53">]>
irb(main):003:0> exit

```
アソシエーションできた

**Comment by MitoShimada** [comment]
Top#indexにメニュー一覧が表示されるようにしました。
自分でissue作っておいてなんだけどmenuだけのindexって消していいんだっけ・・・

**Comment by stivan622** [comment]
@MitoShimada menuコントローラーのindexアクションは消しちゃってOK

**Comment by MitoShimada** [comment]
@stivan622 遅れてごめん、消しといた
