### ISSUE TITLE
メニューお気に入り機能

### ISSUE THREAD

**Issue by stivan622** [fitness-app/fitness_app#8]
# TODO
- [ ] tagsテーブル作成
- [ ] 中間テーブル作成
- [ ] MenuとTagのアソシエーション

参考
#3 
http://labyrinth-of-wisdom.hatenadiary.com/entry/2016/03/03/085059

**Comment by dragonko15296** [comment]
これTODO違うのでチェックボックスつけてないです。いまからプルリクエストおくります。
